name: Generate Activity Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Activity Graph SVG
        run: |
          curl -sL -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" "https://github-readme-activity-graph.vercel.app/graph?username=y-lebid&theme=react-dark&hide_border=true&bg_color=0d1117" -o profile-activity.svg
          
          if [ $(wc -c < profile-activity.svg) -lt 1000 ]; then
            echo "Downloaded file is too small or contains an error response."
            exit 1
          fi

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add profile-activity.svg
          git commit -m "Update activity graph" || exit 0
          git push
