name: Generate Activity Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ashutosh00710/github-readme-activity-graph@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: profile-activity.svg
          theme: react-dark
          bg_color: "0d1117"
          hide_border: "true"
      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add profile-activity.svg
          git commit -m "Update activity graph" || exit 0
          git push
